// app/layout.tsx
import type { Metadata } from "next";
import "leaflet/dist/leaflet.css";
import "../style/globals.css";
import Providers from "./Providers"; // ✅ Import client wrapper

export const metadata: Metadata = {
  title: "Api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers> {/* ✅ wrapped client-side */}
      </body>
    </html>
  );
}
