import type { Metadata } from "next";
import "leaflet/dist/leaflet.css";
import "../style/globals.css";
import { AuthProvider } from "@/AuthContext";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutWrapperProvider from "./LayoutWrapperProvider";

// Import the client component here

export const metadata: Metadata = {
  title: "Api",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Render the LayoutWrapperProvider */}
            <LayoutWrapperProvider>{children}</LayoutWrapperProvider>
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
